spring:
  application:
    name: artificial-intelligence
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    gemini:
      base-url: "https://generativelanguage.googleapis.com/v1/models"
      api-key: ${GEMINI_API_KEY}
